"""Pydantic request and response schemas (PLAN section 4)."""

from hoje.schemas.auth import (
    AuthState,
    EmailLogEntry,
    EmailSettings,
    LoginRequest,
    LoginResponse,
    Me,
    MeUpdate,
    MfaRequest,
    PasswordChange,
    PasswordForgot,
    PasswordReset,
    RecoveryCodes,
    Register,
    TotpConfirmRequest,
    TotpEnableRequest,
    TotpSetupRequest,
    TotpSetupResponse,
)
from hoje.schemas.categories import (
    Category,
    CategoryConflict,
    CategoryCreate,
    CategoryOrder,
    CategoryUpdate,
)
from hoje.schemas.common import HealthStatus, Problem, ProblemError, RealtimeChange
from hoje.schemas.events import (
    Event,
    EventConflict,
    EventCreate,
    EventUpdate,
    EventWithImpact,
    Occurrence,
    OccurrenceList,
    ReminderIn,
    ReminderOut,
    SearchResult,
)
from hoje.schemas.holidays import (
    Holiday,
    HolidayCalendar,
    HolidayCalendarUpdate,
    HolidayCreate,
    HolidayUpdate,
)
from hoje.schemas.leave import (
    LeaveBalance,
    LeaveBooking,
    LeaveImpact,
    LeavePolicy,
    LeavePolicyConflict,
    LeavePolicyUpdate,
    LeavePreviewRequest,
)

__all__ = [
    "AuthState",
    "Category",
    "CategoryConflict",
    "CategoryCreate",
    "CategoryOrder",
    "CategoryUpdate",
    "EmailLogEntry",
    "EmailSettings",
    "Event",
    "EventConflict",
    "EventCreate",
    "EventUpdate",
    "EventWithImpact",
    "HealthStatus",
    "Holiday",
    "HolidayCalendar",
    "HolidayCalendarUpdate",
    "HolidayCreate",
    "HolidayUpdate",
    "LeaveBalance",
    "LeaveBooking",
    "LeaveImpact",
    "LeavePolicy",
    "LeavePolicyConflict",
    "LeavePolicyUpdate",
    "LeavePreviewRequest",
    "LoginRequest",
    "LoginResponse",
    "Me",
    "MeUpdate",
    "MfaRequest",
    "Occurrence",
    "OccurrenceList",
    "PasswordChange",
    "PasswordForgot",
    "PasswordReset",
    "Problem",
    "ProblemError",
    "RealtimeChange",
    "RecoveryCodes",
    "Register",
    "ReminderIn",
    "ReminderOut",
    "SearchResult",
    "TotpConfirmRequest",
    "TotpEnableRequest",
    "TotpSetupRequest",
    "TotpSetupResponse",
]
